{% set name = "go-gum" %}
{% set version = "0.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charmbracelet/gum/archive/v{{ version }}.tar.gz
  sha256: a8f53901447b13613e3445538e2c4d42fd7afb9dad9535debff1b64656b66867

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - gum --help

about:
  home: https://github.com/charmbracelet/gum
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Tool for glamorous shell scripts
  dev_url: https://github.com/charmbracelet/gum

extra:
  recipe-maintainers:
    - danielnachun
