{% set name = "go-gum" %}
{% set version = "0.14.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charmbracelet/gum/archive/v{{ version }}.tar.gz
  sha256: b2c8101bb6f93acba420808df65b3f9acfe8cc9de283c1d9d94311123f43f271

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - gum --help

about:
  home: https://github.com/charmbracelet/gum
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Tool for glamorous shell scripts
  dev_url: https://github.com/charmbracelet/gum

extra:
  recipe-maintainers:
    - danielnachun
