schema_version: 1

context:
  version: "2.0.2"

package:
  name: go-gum
  version: ${{ version }}

source:
  url: https://github.com/charmbracelet/gum/archive/v${{ version }}.tar.gz
  sha256: 06403707671e9b2af386640d8b9f6079efc0aadf77e8f6b091bd191fe16c1264

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gum --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Tool for glamorous shell scripts
  homepage: https://github.com/charmbracelet/gum
  repository: https://github.com/charmbracelet/gum

extra:
  recipe-maintainers:
    - danielnachun
